# Window decorations will be removed when tiling if set to true
remove_decorations = true

# Zentile will ignore windows added to this list.
# You'll have to add WM_CLASS property of the window you want ignored.
# You can get WM_CLASS property of a window, by running "xprop WM_CLASS" and clicking on the window.
# ignore = ['ulauncher', 'gnome-screenshot']

# Adds spacing between windows
gap = 5

# How much to increment the master area size.
proportion = 0.1

[keybindings]
# key sequences can have zero or more modifiers and exactly one key.
# example: Control-Shift-t has two modifiers and one key.
# You can view which keys activate which modifier using the 'xmodmap' program.
# Key symbols can be found by pressing keys using the 'xev' program

# Tile the current workspace.
tile = "Control-Mod4-t"

# Untile the current workspace.
untile = "Control-Mod4-u"

# Make the active window as master.
make_active_window_master = "Control-Mod4-m"

# Increase the number of masters.
increase_master = "Control-Mod4-i"

# Decrease the number of masters.
decrease_master = "Control-Mod4-d"

# Cycles through the available layouts.
switch_layout = "Control-Mod4-s"

# Moves focus to the next window.
next_window = "Control-Mod4-n"

# Moves focus to the previous window.
previous_window = "Control-Mod4-p"

# Increases the size of the master windows.
increment_master = "Control-bracketright"

# Decreases the size of the master windows.
decrement_master = "Control-bracketleft"
